name: sun_envidiado_website
description: "A terminal-like personal website made with Flutter."
publish_to: "none"
version: 1.0.6

environment:
  sdk: ^3.8.1
  flutter: ^3.32.5

dependencies:
  cupertino_icons: ^1.0.8
  firebase_analytics: ^11.5.2
  firebase_core: ^3.15.1
  firebase_crashlytics: ^4.3.9
  flutter:
    sdk: flutter
  flutter_markdown: ^0.7.4+1
  flutter_shaders: ^0.1.3
  google_fonts: ^6.2.1
  markdown: ^7.3.0
  url_launcher: ^6.3.1
  web: ^1.1.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.6
  flutter_test:
    sdk: flutter
  icons_launcher: ^3.0.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/fonts/ibm_vga_8/
    - assets/
  shaders:
    - assets/shaders/crt.glsl

  fonts:
    - family: IBM VGA 8
      fonts:
        - asset: assets/fonts/ibm_vga_8/IBM_VGA_8x16.ttf
          weight: 400

flutter_native_splash:
  color: "#000000"
  image: "assets/splash.png"

icons_launcher:
  image_path: "assets/app_icon.png"
  platforms:
    web:
      enable: true
