name: Run tests

on:
  push:
    branches-ignore:
      - "v*"
    tags-ignore:
      - "v*"
  workflow_dispatch:

jobs:
  verification:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.32.7 # Must be the same with the one in pubspec.yaml

      - name: Download dependencies
        run: flutter pub get

      - name: Configure firebase
        run: |
          npm install -g firebase-tools
          dart pub global activate flutterfire_cli
          flutterfire configure \
            --project=personal-website-terminal-like \
            --platforms=web \
            --token=${{ secrets.FIREBASE_CI_TOKEN }} \
            --out=lib/firebase_options.dart \
            --yes

      - name: Analyze
        run: flutter analyze --no-pub

      - name: Format
        run: dart format --set-exit-if-changed .

      - name: Run tests
        run: flutter test --no-pub --test-randomize-ordering-seed random
